version: '1.0'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Add an environment variable to configure Ollama's host and port in your app
      OLLAMA_HOST: "host.docker.internal"
      OLLAMA_PORT: "11434"
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:5.11
    environment:
      NEO4J_AUTH: neo4j/default_password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data: